name: publish

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - run: npm run build
      - id: get_version
        uses: battila7/get-version-action@v2
      - run: npm --no-git-tag-version version ${{ steps.get_version.outputs.version-without-v }}

      # First release is manual
      - if: steps.get_version.outputs.version-without-v != '1.0.0'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
