name: test
concurrency: "api_interaction"

on:
  push:
    branches:
      - master
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    name: Test project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build
      - run: npm run test
        env:
          PERSONAL_TOKEN: ${{ secrets.TEST_PERSONAL_TOKEN }}
          PURCHASE_CODE: ${{ secrets.TEST_PURCHASE_CODE }}
